version: '3.8'
services:
  configserver:
    build: configserver
    restart: always
    ports:
    - 8071:8071
    environment:
      ENCRYPT_KEY: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo
#    healthcheck:
#      test:  ["CMD", "curl -f http://localhost:8071/actuator/health || exit 1"]
#      interval: 10s
#      timeout: 10s
#      retries: 5
#      start_period: 40s
  licensingservice:
    build: licensing-service
    restart: always
#    depends_on:
#      configserver:
#        condition: service_healthy
    ports:
    - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_HOST: configserver
      REGISTRY_HOST: consul
  consul:
    image: hashicorp/consul:1.11.4
    restart: always
    volumes:
     - ./server1.json:/consul/config/server1.json:ro
     - ./certs/:/consul/config/certs/:ro
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    command: agent
