version: '3'
services:
   configserver:
      build: ./configserver
      ports:
      - 8071:8071
      environment:
         ENCRYPT_KEY: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo
   licensingservice:
      build: ./licensing-service
      depends_on: 
         configserver:
            condition: service_healthy
      ports:
      - 8080:8080
      environment:
         SPRING_PROFILES_ACTIVE: dev
         CONFIG_HOST: configserver

#    networks:
# ----------------
# Orphan comments:
# ----------------
# Was at begin of line:20 :#      backend:
# Was at begin of line:21 :#        aliases: null