version: '3.8'
services:
  configserver:
    build: configserver
    restart: always
    ports:
    - 8071:8071
#    environment:
#      PORT: 8071
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health", "||", "exit", "1"]
#      start_period: 40s
#      interval: 5s
#      timeout: 30s
#      retries: 5
  gatewayserver:
    build: gateway
    restart: always
    ports:
    - 8072:8072
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_HOST: configserver
      REGISTRY_HOST: consul-server
    depends_on:
      configserver:
        condition: service_healthy
  licensingservice:
    build: licensing-service
    restart: always
    depends_on:
      configserver:
        condition: service_healthy
      gatewayserver:
        condition: service_healthy
    ports:
    - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_HOST: configserver
      REGISTRY_HOST: consul-server
  consul-server:
    image: hashicorp/consul:1.11.4
    restart: always
    volumes:
    - ./datacenter-deploy/server.json:/consul/config/server.json:ro
    ports:
    - 8500:8500
    - 8600:8600/tcp
    - 8600:8600/udp
    command: agent
  consul-client:
    image: hashicorp/consul:1.11.4
    restart: always
    volumes:
    - ./datacenter-deploy/client.json:/consul/config/client.json:ro
    command: agent